# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f5fa5e1193ae0ca8bbbb4a1fee9e57f8a56faeb75eb51a465683e8394714f6b02125c16fb70fbf72aae126cd77357e90e886289b1554722db343f047bb984db0

test:
  secret_key_base: 52f9e876f56892337e62831d82e52e29f9c7a3afadcc48e199f56d092f0dc70bb4f3baf855b4705dc3b05d5406f68ccc03d092d00545c0ca7a87110ce97465fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
